### ISSUE TITLE
Develop endpoints for categories and subcategories

### ISSUE THREAD

**Issue by casperlundberg** [M7011E-django-unchained/trading_api#4]
**Categories**
- [x] /getCategory/:id
- [x] /getCategories
- [x] /editCategory/:id
- [x] /deleteCategory/:id
- [x] /createCategory

**Subcategories**
- [x] /getSubcategory/:id
- [x] /getSubcategories/:id
- [x] /getSubcategories
- [x] /editSubcategory/:id
- [x] /deleteSubcategory/:id
- [x] /createSubcategory

**Comment by Kyrne** [comment]
merged in #13
