### ISSUE TITLE
Develop Auction endpoints

### ISSUE THREAD

**Issue by casperlundberg** [M7011E-django-unchained/trading_api#5]
- [x] /getAuctions
- [x] /getAuction/:auctionId
- [x] /getAuctionsByUserId/:userId
- [x] /getAuctionsByCategoryId/:categoryId
- [x] /getAuctionsBySubcategoryId/:subcategoryId
- [x] /editAuction/:auctionId
- [x] /createAuction/
- [x] /deleteAuction/:auctionId
- [x] /deleteAuctions/:userId

**Comment by Kyrne** [comment]
fixed in #13 and 18a46e4
