### ISSUE TITLE
Develop user endpoints

### ISSUE THREAD

**Issue by casperlundberg** [M7011E-django-unchained/trading_api#6]
Fetch profile picture from Amaon S3 server
- [x] #32

authenticate via social media (sso) and using JWT token or similar
- [ ] /authenticate

Authorization level needs to be available from alla endpoints to see if logged in user is allowed to do requested action.
- [ ] /authorize
- [ ] /setAuthorizationLevel/:userId

Other
- [x] /edit/:userId
- [x] /delete/:userId
- [x] /getUsers
- [x] /getUser/:userId
- [x] /createUser

**Comment by Kyrne** [comment]
This is kinda done? If we scrap S3 then it should be considered done

**Comment by casperlundberg** [comment]
We can skip S3, aint't worth the time so mark as done if you feel that's right
